markdown_extensions:
  - attr_list
  - tables
  - md_in_html
  - def_list

site_name: Victor's V. Personal Page
theme:
  name: simple-blog
  theme_style: dark
  logo: assets/logo.png
  components:
    title: false
    footer: false
